name: flutter_sandbox
description: A new Flutter application.


dependencies:
  flutter:
    sdk: flutter
  font_awesome_flutter: "^6.0.0"
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.0
  http: "^0.11.3+16"
  intl: "^0.15.6"
  transparent_image: "^0.1.0"
  cached_network_image: "^0.3.0"
  rxdart: "^0.16.7"
  url_launcher: "^3.0.0"
  redux: "^3.0.0"
  flutter_redux: "^0.5.2"
  qr_flutter: "^1.0.0"
  redux_epics: "^0.9.0"
  fluttery: "^0.0.5"
  flutter_webview_plugin: "^0.1.4"
  carousel: "^0.1.0"
  battery: "^0.2.0"
  connectivity: "^0.3.0"
  device_info: "^0.2.0"
  hex: "^0.1.1"
  flutter_stream_friends: 0.8.0
  spritewidget: "^0.9.16"
  fluttery_audio: 0.0.3
  image_picker:
  rx_command:
  font_awesome:
  geolocation: ^0.2.1
  flutter_map:
  country_code_picker:





dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
  assets:
  - assets/data/regular_units.json
  - assets/home/background.png
  - assets/home/Logo.png
  - assets/home/Title.png
  - assets/TabBar/about.png
  - assets/explore/Background.png
  - assets/explore/Title.png
  - assets/explore/TinderCard.png
  - assets/uncover/background_uncover.png
  - assets/uncover/uncover_evolution_card.png
  - assets/uncover/uncover_origin_card.png
  - assets/uncover/uncover_tecnique_card.png
  - assets/uncover/uncover_trivia_card.png
  - assets/uncover/title.png
  - assets/profile/emma-watson.jpg
  - assets/profile/microphone.png
  - assets/profile/wallet.png
  - assets/profile/joystick.png
  - assets/landing/banks.png
  - assets/landing/hotels.png
  - assets/landing/key.png
  - assets/landing/shopping_cart.png
  - assets/landing/stores.png
  - assets/landing/wallet.png
  - assets/images/flutter-mark-square-64.png
  - assets/images/coffee_header.jpeg
  - assets/data/sample.json
  - assets/images/profile_header_background.png
  - assets/images/portfolio_1.jpeg
  - assets/images/portfolio_2.jpeg
  - assets/images/portfolio_3.jpeg
  - assets/images/portfolio_4.jpeg
  - assets/images/portfolio_5.jpeg
  - assets/images/portfolio_6.jpeg
  - assets/artistscreen/avatar.png
  - assets/artistscreen/backdrop.png
  - assets/artistscreen/video1_thumb.png
  - assets/artistscreen/video4_thumb.png
  - assets/artistscreen/video3_thumb.png
  - assets/artistscreen/video2_thumb.png
  - assets/wallpaper/wallpaper1.jpg
  - assets/wallpaper/wallpaper2.jpg
  - assets/wallpaper/wallpaper3.jpg
  - assets/materialpage/banks.png
  - assets/materialpage/hotels.png
  - assets/materialpage/key.old.png
  - assets/materialpage/key.png
  - assets/materialpage/shopping_cart.old.png
  - assets/materialpage/shopping_cart.png
  - assets/materialpage/stores.png
  - assets/materialpage/wallet.old.png
  - assets/materialpage/wallet.png
  - assets/restaurantanimation/angry.gif
  - assets/restaurantanimation/bg_uit.jpg
  - assets/restaurantanimation/chair_bottom.png
  - assets/restaurantanimation/chair_top.png
  - assets/restaurantanimation/chicken.png
  - assets/restaurantanimation/clap.png
  - assets/restaurantanimation/clap_border.png
  - assets/restaurantanimation/curry.png
  - assets/restaurantanimation/duck.png
  - assets/restaurantanimation/flan.png
  - assets/restaurantanimation/haha.gif
  - assets/restaurantanimation/ic_add.png
  - assets/restaurantanimation/ic_add_circle.png
  - assets/restaurantanimation/ic_avatar.png
  - assets/restaurantanimation/ic_book.png
  - assets/restaurantanimation/ic_cake.png
  - assets/restaurantanimation/ic_camera.png
  - assets/restaurantanimation/ic_cancel.png
  - assets/restaurantanimation/ic_car.png
  - assets/restaurantanimation/ic_clock.png
  - assets/restaurantanimation/ic_coffee.png
  - assets/restaurantanimation/ic_cook.png
  - assets/restaurantanimation/ic_home.png
  - assets/restaurantanimation/ic_jupiter.png
  - assets/restaurantanimation/ic_like.png
  - assets/restaurantanimation/ic_like_fill.png
  - assets/restaurantanimation/ic_mars.png
  - assets/restaurantanimation/ic_menu.png
  - assets/restaurantanimation/ic_mercury.png
  - assets/restaurantanimation/ic_moon.png
  - assets/restaurantanimation/ic_neptune.png
  - assets/restaurantanimation/ic_red_circle.png
  - assets/restaurantanimation/ic_remove_circle.png
  - assets/restaurantanimation/ic_restaurant.png
  - assets/restaurantanimation/ic_saturn.png
  - assets/restaurantanimation/ic_seat.png
  - assets/restaurantanimation/ic_uranus.png
  - assets/restaurantanimation/ic_venus.png
  - assets/restaurantanimation/ic_white_circle.png
  - assets/restaurantanimation/like.gif
  - assets/restaurantanimation/logo_uit.png
  - assets/restaurantanimation/love.gif
  - assets/restaurantanimation/pizza.png
  - assets/restaurantanimation/sad.gif
  - assets/restaurantanimation/salad.png
  - assets/restaurantanimation/shadow_white.png
  - assets/restaurantanimation/sparkles.png
  - assets/restaurantanimation/table_big_green.png
  - assets/restaurantanimation/table_big_pink.png
  - assets/restaurantanimation/table_small_green.png
  - assets/restaurantanimation/table_small_yellow.png
  - assets/restaurantanimation/wow.gif
  - assets/hiddenmenu/dark_grunge_bk.jpg
  - assets/hiddenmenu/eggs_in_skillet.jpg
  - assets/hiddenmenu/other_screen_bk.jpg
  - assets/hiddenmenu/other_screen_card_photo.jpg
  - assets/hiddenmenu/spoons_of_spices.jpg
  - assets/hiddenmenu/steak_on_cooktop.jpg
  - assets/hiddenmenu/wood_bk.jpg
  - assets/materialpage/problemstatment.png
  - assets/map/map.png
  - assets/circlek/fastfood.jpeg
  - assets/circlek/icecream.jpg
  - assets/circlek/noodles.jpeg
  - assets/circlek/numbella.jpg
  - assets/circlek/circlelogo.png
  - assets/circlek/map.jpg
  - assets/weather/ic_cloudy.png
  - assets/weather/ic_rain.png
  - assets/weather/ic_sunny.png
  - assets/weather/weather-bk.png
  - assets/weather/weather-bk_enlarged.png
  - assets/weather/weathersprites.json
  - assets/weather/weathersprites.png
  - assets/flipcarousel/board_walk.jpg
  - assets/flipcarousel/dusk_waves.jpg
  - assets/flipcarousel/van_on_beach.jpg
  - assets/tinder/photo_1.jpg
  - assets/tinder/photo_2.jpg
  - assets/tinder/photo_3.jpg
  - assets/tinder/photo_4.jpg
  - assets/WavePath/coffee_bottom_clip_points.png
  - assets/WavePath/coffee_header.jpeg
  - assets/Beer/cider.png
  - assets/Beer/copper.png
  - assets/Beer/deception.png
  - assets/Beer/luxe.png
  - assets/Beer/maximus.png
  - assets/Beer/pilsnah.png
  - assets/Beer/porternoir.png
  - assets/Beer/session.png
  - assets/Beer/statesman.png
  - assets/Beer/stuntman.png
  - assets/planet/earth.png
  - assets/planet/ic_distance.png
  - assets/planet/ic_gravity.png
  - assets/planet/mars.png
  - assets/planet/mercury.png
  - assets/planet/moon.png
  - assets/planet/neptune.png
  - assets/Coffee/coffee_in_bed.jpg
  - assets/uikit/blank.jpg
  - assets/uikit/dashboard.jpg
  - assets/uikit/login.jpg
  - assets/uikit/map.png
  - assets/uikit/payment.jpg
  - assets/uikit/pk.jpg
  - assets/uikit/profile.jpg
  - assets/uikit/setting.jpeg
  - assets/uikit/shopping.jpeg
  - assets/uikit/timeline.jpeg
  - assets/uikit/verification.jpg
  - assets/travelscreen/beach1.jpg
  - assets/travelscreen/beach2.jpg
  - assets/travelscreen/beach3.jpg
  - assets/travelscreen/chatbubble.png
  - assets/travelscreen/chris.jpg
  - assets/travelscreen/fav.png
  - assets/travelscreen/navarrow.png
  - assets/travelscreen/speechbubble.png
  - assets/login/logotwo.png
  - assets/flags/tg.png
  - assets/flags/me.png
  - assets/flags/la.png
  - assets/flags/mr.png
  - assets/flags/ni.png
  - assets/flags/lv.png
  - assets/flags/om.png
  - assets/flags/af.png
  - assets/flags/cy.png
  - assets/flags/bj.png
  - assets/flags/aq.png
  - assets/flags/cn.png
  - assets/flags/gb-sct.png
  - assets/flags/co.png
  - assets/flags/cx.png
  - assets/flags/ag.png
  - assets/flags/ms.png
  - assets/flags/md.png
  - assets/flags/zm.png
  - assets/flags/vn.png
  - assets/flags/tf.png
  - assets/flags/td.png
  - assets/flags/yt.png
  - assets/flags/lb.png
  - assets/flags/mf.png
  - assets/flags/lu.png
  - assets/flags/mq.png
  - assets/flags/cz.png
  - assets/flags/ae.png
  - assets/flags/cm.png
  - assets/flags/bi.png
  - assets/flags/ar.png
  - assets/flags/as.png
  - assets/flags/bh.png
  - assets/flags/cl.png
  - assets/flags/ad.png
  - assets/flags/mp.png
  - assets/flags/lt.png
  - assets/flags/mg.png
  - assets/flags/lc.png
  - assets/flags/tr.png
  - assets/flags/ua.png
  - assets/flags/tv.png
  - assets/flags/vi.png
  - assets/flags/mt.png
  - assets/flags/no.png
  - assets/flags/mc.png
  - assets/flags/ch.png
  - assets/flags/bl.png
  - assets/flags/aw.png
  - assets/flags/bz.png
  - assets/flags/bm.png
  - assets/flags/ci.png
  - assets/flags/mu.png
  - assets/flags/us.png
  - assets/flags/tw.png
  - assets/flags/ye.png
  - assets/flags/mw.png
  - assets/flags/nl.png
  - assets/flags/ls.png
  - assets/flags/bo.png
  - assets/flags/at.png
  - assets/flags/ck.png
  - assets/flags/by.png
  - assets/flags/au.png
  - assets/flags/bn.png
  - assets/flags/ma.png
  - assets/flags/nz.png
  - assets/flags/lr.png
  - assets/flags/mv.png
  - assets/flags/tc.png
  - assets/flags/ug.png
  - assets/flags/tt.png
  - assets/flags/pl.png
  - assets/flags/rs.png
  - assets/flags/in.png
  - assets/flags/ge.png
  - assets/flags/gr.png
  - assets/flags/gs.png
  - assets/flags/gd.png
  - assets/flags/io.png
  - assets/flags/hk.png
  - assets/flags/kp.png
  - assets/flags/gb-nir.png
  - assets/flags/kg.png
  - assets/flags/pm.png
  - assets/flags/sv.png
  - assets/flags/re.png
  - assets/flags/sa.png
  - assets/flags/sc.png
  - assets/flags/st.png
  - assets/flags/ke.png
  - assets/flags/im.png
  - assets/flags/kr.png
  - assets/flags/gf.png
  - assets/flags/dj.png
  - assets/flags/gq.png
  - assets/flags/gp.png
  - assets/flags/dk.png
  - assets/flags/gg.png
  - assets/flags/il.png
  - assets/flags/pn.png
  - assets/flags/sb.png
  - assets/flags/py.png
  - assets/flags/ru.png
  - assets/flags/kw.png
  - assets/flags/do.png
  - assets/flags/gt.png
  - assets/flags/gb.png
  - assets/flags/gu.png
  - assets/flags/je.png
  - assets/flags/hm.png
  - assets/flags/sg.png
  - assets/flags/pk.png
  - assets/flags/sr.png
  - assets/flags/se.png
  - assets/flags/jp.png
  - assets/flags/gw.png
  - assets/flags/eh.png
  - assets/flags/dz.png
  - assets/flags/ga.png
  - assets/flags/fr.png
  - assets/flags/dm.png
  - assets/flags/hn.png
  - assets/flags/sd.png
  - assets/flags/rw.png
  - assets/flags/ph.png
  - assets/flags/ss.png
  - assets/flags/qa.png
  - assets/flags/pe.png
  - assets/flags/pr.png
  - assets/flags/si.png
  - assets/flags/ht.png
  - assets/flags/es.png
  - assets/flags/gl.png
  - assets/flags/gm.png
  - assets/flags/er.png
  - assets/flags/fi.png
  - assets/flags/ee.png
  - assets/flags/kn.png
  - assets/flags/hu.png
  - assets/flags/iq.png
  - assets/flags/ky.png
  - assets/flags/sh.png
  - assets/flags/ps.png
  - assets/flags/pf.png
  - assets/flags/sj.png
  - assets/flags/id.png
  - assets/flags/is.png
  - assets/flags/eg.png
  - assets/flags/fk.png
  - assets/flags/fj.png
  - assets/flags/gn.png
  - assets/flags/gy.png
  - assets/flags/ir.png
  - assets/flags/km.png
  - assets/flags/ie.png
  - assets/flags/kz.png
  - assets/flags/ro.png
  - assets/flags/sk.png
  - assets/flags/pg.png
  - assets/flags/pt.png
  - assets/flags/so.png
  - assets/flags/sx.png
  - assets/flags/hr.png
  - assets/flags/ki.png
  - assets/flags/jm.png
  - assets/flags/eu.png
  - assets/flags/ec.png
  - assets/flags/et.png
  - assets/flags/fo.png
  - assets/flags/kh.png
  - assets/flags/sy.png
  - assets/flags/sn.png
  - assets/flags/pw.png
  - assets/flags/sl.png
  - assets/flags/gb-eng.png
  - assets/flags/fm.png
  - assets/flags/gi.png
  - assets/flags/de.png
  - assets/flags/gh.png
  - assets/flags/jo.png
  - assets/flags/it.png
  - assets/flags/pa.png
  - assets/flags/sz.png
  - assets/flags/sm.png
  - assets/flags/tn.png
  - assets/flags/ml.png
  - assets/flags/cg.png
  - assets/flags/ax.png
  - assets/flags/ao.png
  - assets/flags/bt.png
  - assets/flags/bb.png
  - assets/flags/cf.png
  - assets/flags/mm.png
  - assets/flags/li.png
  - assets/flags/na.png
  - assets/flags/mz.png
  - assets/flags/to.png
  - assets/flags/vg.png
  - assets/flags/ve.png
  - assets/flags/tz.png
  - assets/flags/tm.png
  - assets/flags/mx.png
  - assets/flags/nc.png
  - assets/flags/mo.png
  - assets/flags/lk.png
  - assets/flags/cd.png
  - assets/flags/al.png
  - assets/flags/bw.png
  - assets/flags/cr.png
  - assets/flags/bv.png
  - assets/flags/am.png
  - assets/flags/az.png
  - assets/flags/ba.png
  - assets/flags/mn.png
  - assets/flags/nu.png
  - assets/flags/my.png
  - assets/flags/tl.png
  - assets/flags/ws.png
  - assets/flags/th.png
  - assets/flags/xk.png
  - assets/flags/nf.png
  - assets/flags/ly.png
  - assets/flags/ai.png
  - assets/flags/br.png
  - assets/flags/cv.png
  - assets/flags/be.png
  - assets/flags/ca.png
  - assets/flags/bd.png
  - assets/flags/cw.png
  - assets/flags/bs.png
  - assets/flags/ng.png
  - assets/flags/mk.png
  - assets/flags/np.png
  - assets/flags/va.png
  - assets/flags/uz.png
  - assets/flags/um.png
  - assets/flags/tk.png
  - assets/flags/vc.png
  - assets/flags/zw.png
  - assets/flags/nr.png
  - assets/flags/ne.png
  - assets/flags/cu.png
  - assets/flags/bq.png
  - assets/flags/bf.png
  - assets/flags/bg.png
  - assets/flags/cc.png
  - assets/flags/gb-wls.png
  - assets/flags/mh.png
  - assets/flags/za.png
  - assets/flags/uy.png
  - assets/flags/wf.png
  - assets/flags/vu.png
  - assets/flags/tj.png
  - assets/flags/an.png
  - assets/converter/icons/area.png
  - assets/converter/icons/currency.png
  - assets/converter/icons/digital_storage.png
  - assets/converter/icons/length.png
  - assets/converter/icons/mass.png
  - assets/converter/icons/power.png
  - assets/converter/icons/time.png
  - assets/converter/icons/volume.png


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
   - family: Quicksand
     fonts:
          - asset: assets/fonts/Quicksand-Medium.ttf
          - asset: assets/fonts/Quicksand-Bold.ttf
            weight: 700

   - family: Montserrat
     fonts:
          - asset: assets/fonts/Montserrat-Regular.ttf
          - asset: assets/fonts/Montserrat-Bold.ttf
            weight: 700
   - family: petita
     fonts:
          - asset: assets/fonts/PetitaMedium.ttf
          - asset: assets/fonts/PetitaBold.ttf
            weight: 700
          - asset: assets/fonts/PetitaLight.ttf
            weight: 300
   - family: gidole
     fonts:
         - asset: assets/fonts/Gidole-Regular.ttf
   - family: BebasNeue
     fonts:
          - asset: assets/fonts/BebasNeue-Regular.ttf
   - family: bebas-neue
     fonts:
          - asset: assets/hiddenmenu/BebasNeue-Regular.ttf
   - family: FlamanteRoma
     fonts:
          - asset: assets/materialpage/fonts/Flamante-Roma-Medium.ttf
          - asset: assets/materialpage/fonts/Flamante-Roma-MediumItalic.ttf
   - family: icomoon
     fonts:
       - asset: assets/fonts/icomoon.ttf
   - family: Themify
     fonts:
       - asset: assets/fonts/themify.ttf
   - family: LineAwesome
     fonts:
       - asset: assets/fonts/line-awesome.ttf
   - family: Timeburner
     fonts:
       - asset: assets/fonts/timeburnernormal.ttf
       - asset: assets/fonts/timeburnerbold.ttf
         weight: 700
   - family: Poppins
     fonts:
       - asset: assets/fonts/Poppins-SemiBold.ttf
         weight: 600
       - asset: assets/fonts/Poppins-Regular.ttf
         weight: 400
   - family: FlamanteRoma
     fonts:
       - asset: assets/fonts/Flamante-Roma-Medium.ttf
       - asset: assets/fonts/Flamante-Roma-MediumItalic.ttf
         style: italic


  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
