name: flutter_sandbox
description: A new Flutter application.

dependencies:
  flutter:
    sdk: flutter
  font_awesome_flutter: "^6.0.0"
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.0
  http: "^0.11.3+16"
  intl: "^0.15.6"
  transparent_image: "^0.1.0"
  cached_network_image: "^0.3.0"
  rxdart: "^0.16.7"
  url_launcher: "^3.0.0"
  redux: "^3.0.0"
  flutter_redux: "^0.5.2"
  qr_flutter: "^1.0.0"
  redux_epics: "^0.9.0"
  fluttery: "^0.0.5"
  flutter_webview_plugin: "^0.1.4"
  carousel: "^0.1.0"
  battery: "^0.2.0"
  connectivity: "^0.3.0"
  device_info: "^0.2.0"
  hex: "^0.1.1"
  flutter_stream_friends: 0.8.0
  spritewidget: "^0.9.16"
  fluttery_audio: 0.0.3
  image_picker:
  rx_command:
  font_awesome:
  geolocation: ^0.2.1
  flutter_map:




dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
  assets:
  - assets/home/background.png
  - assets/home/Logo.png
  - assets/home/Title.png
  - assets/TabBar/about.png
  - assets/explore/Background.png
  - assets/explore/Title.png
  - assets/explore/TinderCard.png
  - assets/uncover/background_uncover.png
  - assets/uncover/uncover_evolution_card.png
  - assets/uncover/uncover_origin_card.png
  - assets/uncover/uncover_tecnique_card.png
  - assets/uncover/uncover_trivia_card.png
  - assets/uncover/title.png
  - assets/profile/emma-watson.jpg
  - assets/profile/microphone.png
  - assets/profile/wallet.png
  - assets/profile/joystick.png
  - assets/landing/banks.png
  - assets/landing/hotels.png
  - assets/landing/key.png
  - assets/landing/shopping_cart.png
  - assets/landing/stores.png
  - assets/landing/wallet.png
  - assets/images/flutter-mark-square-64.png
  - assets/images/coffee_header.jpeg
  - assets/data/sample.json
  - assets/images/profile_header_background.png
  - assets/images/portfolio_1.jpeg
  - assets/images/portfolio_2.jpeg
  - assets/images/portfolio_3.jpeg
  - assets/images/portfolio_4.jpeg
  - assets/images/portfolio_5.jpeg
  - assets/images/portfolio_6.jpeg
  - assets/artistscreen/avatar.png
  - assets/artistscreen/backdrop.png
  - assets/artistscreen/video1_thumb.png
  - assets/artistscreen/video4_thumb.png
  - assets/artistscreen/video3_thumb.png
  - assets/artistscreen/video2_thumb.png
  - assets/wallpaper/wallpaper1.jpg
  - assets/wallpaper/wallpaper2.jpg
  - assets/wallpaper/wallpaper3.jpg
  - assets/materialpage/banks.png
  - assets/materialpage/hotels.png
  - assets/materialpage/key.old.png
  - assets/materialpage/key.png
  - assets/materialpage/shopping_cart.old.png
  - assets/materialpage/shopping_cart.png
  - assets/materialpage/stores.png
  - assets/materialpage/wallet.old.png
  - assets/materialpage/wallet.png
  - assets/restaurantanimation/angry.gif
  - assets/restaurantanimation/bg_uit.jpg
  - assets/restaurantanimation/chair_bottom.png
  - assets/restaurantanimation/chair_top.png
  - assets/restaurantanimation/chicken.png
  - assets/restaurantanimation/clap.png
  - assets/restaurantanimation/clap_border.png
  - assets/restaurantanimation/curry.png
  - assets/restaurantanimation/duck.png
  - assets/restaurantanimation/flan.png
  - assets/restaurantanimation/haha.gif
  - assets/restaurantanimation/ic_add.png
  - assets/restaurantanimation/ic_add_circle.png
  - assets/restaurantanimation/ic_avatar.png
  - assets/restaurantanimation/ic_book.png
  - assets/restaurantanimation/ic_cake.png
  - assets/restaurantanimation/ic_camera.png
  - assets/restaurantanimation/ic_cancel.png
  - assets/restaurantanimation/ic_car.png
  - assets/restaurantanimation/ic_clock.png
  - assets/restaurantanimation/ic_coffee.png
  - assets/restaurantanimation/ic_cook.png
  - assets/restaurantanimation/ic_home.png
  - assets/restaurantanimation/ic_jupiter.png
  - assets/restaurantanimation/ic_like.png
  - assets/restaurantanimation/ic_like_fill.png
  - assets/restaurantanimation/ic_mars.png
  - assets/restaurantanimation/ic_menu.png
  - assets/restaurantanimation/ic_mercury.png
  - assets/restaurantanimation/ic_moon.png
  - assets/restaurantanimation/ic_neptune.png
  - assets/restaurantanimation/ic_red_circle.png
  - assets/restaurantanimation/ic_remove_circle.png
  - assets/restaurantanimation/ic_restaurant.png
  - assets/restaurantanimation/ic_saturn.png
  - assets/restaurantanimation/ic_seat.png
  - assets/restaurantanimation/ic_uranus.png
  - assets/restaurantanimation/ic_venus.png
  - assets/restaurantanimation/ic_white_circle.png
  - assets/restaurantanimation/like.gif
  - assets/restaurantanimation/logo_uit.png
  - assets/restaurantanimation/love.gif
  - assets/restaurantanimation/pizza.png
  - assets/restaurantanimation/sad.gif
  - assets/restaurantanimation/salad.png
  - assets/restaurantanimation/shadow_white.png
  - assets/restaurantanimation/sparkles.png
  - assets/restaurantanimation/table_big_green.png
  - assets/restaurantanimation/table_big_pink.png
  - assets/restaurantanimation/table_small_green.png
  - assets/restaurantanimation/table_small_yellow.png
  - assets/restaurantanimation/wow.gif
  - assets/hiddenmenu/dark_grunge_bk.jpg
  - assets/hiddenmenu/eggs_in_skillet.jpg
  - assets/hiddenmenu/other_screen_bk.jpg
  - assets/hiddenmenu/other_screen_card_photo.jpg
  - assets/hiddenmenu/spoons_of_spices.jpg
  - assets/hiddenmenu/steak_on_cooktop.jpg
  - assets/hiddenmenu/wood_bk.jpg
  - assets/materialpage/problemstatment.png
  - assets/map/map.png
  - assets/circlek/fastfood.jpeg
  - assets/circlek/icecream.jpg
  - assets/circlek/noodles.jpeg
  - assets/circlek/numbella.jpg
  - assets/circlek/circlelogo.png
  - assets/circlek/map.jpg
  - assets/weather/ic_cloudy.png
  - assets/weather/ic_rain.png
  - assets/weather/ic_sunny.png
  - assets/weather/weather-bk.png
  - assets/weather/weather-bk_enlarged.png
  - assets/weather/weathersprites.json
  - assets/weather/weathersprites.png
  - assets/flipcarousel/board_walk.jpg
  - assets/flipcarousel/dusk_waves.jpg
  - assets/flipcarousel/van_on_beach.jpg
  - assets/tinder/photo_1.jpg
  - assets/tinder/photo_2.jpg
  - assets/tinder/photo_3.jpg
  - assets/tinder/photo_4.jpg
  - assets/WavePath/coffee_bottom_clip_points.png
  - assets/WavePath/coffee_header.jpeg
  - assets/Beer/cider.png
  - assets/Beer/copper.png
  - assets/Beer/deception.png
  - assets/Beer/luxe.png
  - assets/Beer/maximus.png
  - assets/Beer/pilsnah.png
  - assets/Beer/porternoir.png
  - assets/Beer/session.png
  - assets/Beer/statesman.png
  - assets/Beer/stuntman.png
  - assets/planet/earth.png
  - assets/planet/ic_distance.png
  - assets/planet/ic_gravity.png
  - assets/planet/mars.png
  - assets/planet/mercury.png
  - assets/planet/moon.png
  - assets/planet/neptune.png
  - assets/Coffee/coffee_in_bed.jpg
  - assets/uikit/blank.jpg
  - assets/uikit/dashboard.jpg
  - assets/uikit/login.jpg
  - assets/uikit/map.png
  - assets/uikit/payment.jpg
  - assets/uikit/pk.jpg
  - assets/uikit/profile.jpg
  - assets/uikit/setting.jpeg
  - assets/uikit/shopping.jpeg
  - assets/uikit/timeline.jpeg
  - assets/uikit/verification.jpg
  - assets/travelscreen/beach1.jpg
  - assets/travelscreen/beach2.jpg
  - assets/travelscreen/beach3.jpg
  - assets/travelscreen/chatbubble.png
  - assets/travelscreen/chris.jpg
  - assets/travelscreen/fav.png
  - assets/travelscreen/navarrow.png
  - assets/travelscreen/speechbubble.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
   - family: Montserrat
     fonts:
          - asset: assets/fonts/Montserrat-Regular.ttf
          - asset: assets/fonts/Montserrat-Bold.ttf
            weight: 700
   - family: petita
     fonts:
          - asset: assets/fonts/PetitaMedium.ttf
          - asset: assets/fonts/PetitaBold.ttf
            weight: 700
          - asset: assets/fonts/PetitaLight.ttf
            weight: 300
   - family: gidole
     fonts:
         - asset: assets/fonts/Gidole-Regular.ttf
   - family: BebasNeue
     fonts:
          - asset: assets/fonts/BebasNeue-Regular.ttf
   - family: bebas-neue
     fonts:
          - asset: assets/hiddenmenu/BebasNeue-Regular.ttf
   - family: FlamanteRoma
     fonts:
          - asset: assets/materialpage/fonts/Flamante-Roma-Medium.ttf
          - asset: assets/materialpage/fonts/Flamante-Roma-MediumItalic.ttf
   - family: icomoon
     fonts:
       - asset: assets/fonts/icomoon.ttf
   - family: Themify
     fonts:
       - asset: assets/fonts/themify.ttf
   - family: LineAwesome
     fonts:
       - asset: assets/fonts/line-awesome.ttf
   - family: Timeburner
     fonts:
       - asset: assets/fonts/timeburnernormal.ttf
       - asset: assets/fonts/timeburnerbold.ttf
         weight: 700
   - family: Poppins
     fonts:
       - asset: assets/fonts/Poppins-SemiBold.ttf
         weight: 600
       - asset: assets/fonts/Poppins-Regular.ttf
         weight: 400
   - family: FlamanteRoma
     fonts:
       - asset: assets/fonts/Flamante-Roma-Medium.ttf
       - asset: assets/fonts/Flamante-Roma-MediumItalic.ttf
         style: italic


  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
